:imagesdir: images
:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:stem: Формула
:sourcedir: CODE


== Дизайн

Для корректной работы устройства необходимо произвести настройки используемых модулей.

=== Настройка подключения прецизионного термо-чувствительного кварцевого резонатора

Для подключения прецизионного термочувствительного кварцевого резонатора необходимо:

* Записать по адресу регистра GPIOA_MODER необходимые биты (подключить порт PA0).

=== Настройка подключения таймпера TIM2

* Таймер 2 тактируется от шины APB1.

* Подключение к системе тактирование выполняется через регистр APB1ENR модуля RCC.

* Включение таймера производиться с помощью бита CEN в регистре CR1 модуля таймера.

=== Настройка подключения RTC

Для обеспечения периодичности измерений частоты и преобразования ее в показания гликемии необходимо настроить независимый таймер RTC (Real-time clock):

* Для функции пробуждения необходимо установить бит WUTE в регистре RTC_CR, а также значение этого бита
* установить WUTWF в регистре RTC_ISR
* запрограммировать значение автоматической перезагрузки при пробуждении WUT[15:0 и выбрать время пробуждения (установить биты WUCKSEL[2:0] в регистре RTC_CR)]

=== Настройка подключения интерфейса USART2 для Bluetooth

* Подключить USART к источнику тактирования – устанавливаем бит USART2EN в регистре APB1ENR (АЦП тактируется от матрицы шин APB1).​
* Необходимо сконфигурировать порты. Настроить порты, на альтернативную функцию нужного модуля USART​
* Настроить формат передачи байт, с помощью регистра CR1 и CR2​
* Задать скорость передачи с помощью регистра BRR​
* Разрешить передачу помощью бита TE и если надо прием, с помощью бита RE в модуле USART с помощью регистра CR1​
* Включить сам модуль USART битом UE  в регистре CR1​
* Если работаем через прерывание, то разрешить глобальное прерывание для нужного USART, в регистре ISER[1] модуля NVIC​
* Если работаем через прерывание, в зависимости от того, что нам нужно, разрешить прерывание по сигналу модуля UART (например, от сигнала регистр данных передачика пуст (бит TXEIE в регистре CR1))



=== Архитектура
По полученным результатам анаализа требований была составлена архитектура программного обеспечения устройства.

[#Основная UML-диаграмма]
.Основная UML-диаграмма
[plantuml,format=png]
....
include::UMLMain.puml[]
....

*_Описание:_* Для измерении уровня гликемии устройство обращается к классу данной задачи (MeasureGlycemiaTask), которая в свою очередь забирает значение гликемии (Glycemia) пересчитанное из значений темературы (Temperature), которые в свою очередь пересчитываются из значений измеренного изменения частоты (Frequency) через интерфейс ICalculate.

Для информирования пользователя об уровне заряда батареи (для своевременной замены источника питания) используется класс задачи BatteryTask, который также чрез интерфейс ICalculate получает пересчитанное значение уровня заряда батареи (BatteryVoltage).

Обе задачи выполняются с периодичностью раз в 5 минут

Для передачи информации по Bluetooth создан класс данной задачи (BluetoothTask), данная задача через интерфейся IConverter и IBluetooth выполняет две функции:
1. IConverter - преобразование информации в строку (для возможности передачи данных)
2. IBluetooth - Отправка запрошенной информации по беспроводному интерфейсу Bluetooth.

Для описания каждой функции создана отдельная архитектура (см. UML-диаграмма Bluetooth. Transmitor) и (см. UML-диаграмма Bluetooth. DataProvider).

[#UML-диаграмма Bluetooth. Transmitor]
.UML-диаграмма Bluetooth. Transmitor
[plantuml,format=png]
....
include::UMLTransmitor.puml[]
....

*_Описание:_* для передачи информации по Bluetooth (с помощью класса задачи (BluetoothTask)) данные должны быть отправлены через интерфейс IBluetooth. Для этого класс USART2 преобразует информацию для передачи данных в общую "строку" (с помощью интерфейса IUSART) и через класс Transmitor отправляет по интерфейсу IBluetooth

//[#Основная UML-диаграмма]
//.Основная UML-диаграмма
//[plantuml,format=png]
//....
//include::Diagram.puml[]
//....

//[#UML-диаграмма измерения частоты]
//.UML-диаграмма измерения частоты
//[plantuml,format=png]
//....
//include::PodDiagram.puml[]
//....