:imagesdir: images
:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:stem: Формула


== Дизайн

Для корректной работы устройства необходимо произвести настройки используемых модулей.

=== Настройка подключения прецизионного термо-чувствительного кварцевого резонатора

Для подключения прецизионного термочувствительного кварцевого резонатора необходимо:

* Записать по адресу регистра GPIOA_MODER необходимые биты (подключить порт PA0).

=== Настройка подключения таймпера TIM2

* Таймер 2 тактируется от шины APB1.

* Подключение к системе тактирование выполняется через регистр APB1ENR модуля RCC.

* Включение таймера производиться с помощью бита CEN в регистре CR1 модуля таймера.

=== Настройка подключения RTC

Для обеспечения периодичности измерений частоты и преобразования ее в показания гликемии необходимо настроить независимый таймер RTC (Real-time clock):

* Для функции пробуждения необходимо установить бит WUTE в регистре RTC_CR, а также значение этого бита
* установить WUTWF в регистре RTC_ISR
* запрограммировать значение автоматической перезагрузки при пробуждении WUT[15:0 и выбрать время пробуждения (установить биты WUCKSEL[2:0] в регистре RTC_CR)]

=== Настройка подключения интерфейса USART2 для Bluetooth

* Подключить USART к источнику тактирования – устанавливаем бит USART2EN в регистре APB1ENR (АЦП тактируется от матрицы шин APB1).​
* Необходимо сконфигурировать порты. Настроить порты, на альтернативную функцию нужного модуля USART​
* Настроить формат передачи байт, с помощью регистра CR1 и CR2​
* Задать скорость передачи с помощью регистра BRR​
* Разрешить передачу помощью бита TE и если надо прием, с помощью бита RE в модуле USART с помощью регистра CR1​
* Включить сам модуль USART битом UE  в регистре CR1​
* Если работаем через прерывание, то разрешить глобальное прерывание для нужного USART, в регистре ISER[1] модуля NVIC​
* Если работаем через прерывание, в зависимости от того, что нам нужно, разрешить прерывание по сигналу модуля UART (например,
  от сигнала регистр данных передачика пуст (бит TXEIE в регистре CR1))


=== Архитектура
По полученным результатам анаализа требований была составлена архитектура программного обеспечения устройства.

[#Основная UML-диаграмма]
.Основная UML-диаграмма
[plantuml,format=png]
....
include::Diagram.puml[]
....

[#UML-диаграмма измерения частоты]
.UML-диаграмма измерения частоты
[plantuml,format=png]
....
include::PodDiagram.puml[]
....