:imagesdir: images
:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:stem: Формула
:sourcedir: CODE


== Дизайн

Для корректной работы устройства необходимо произвести настройки используемых модулей.

=== Настройка подключения прецизионного термо-чувствительного кварцевого резонатора

Для подключения прецизионного термочувствительного кварцевого резонатора необходимо:

* Записать по адресу регистра GPIOA_MODER необходимые биты (подключить порт PA0).

=== Настройка подключения таймпера TIM2

* Таймер 2 тактируется от шины APB1.

* Подключение к системе тактирование выполняется через регистр APB1ENR модуля RCC.

* Включение таймера производиться с помощью бита CEN в регистре CR1 модуля таймера.

=== Настройка подключения RTC

Для обеспечения периодичности измерений частоты и преобразования ее в показания гликемии необходимо настроить независимый таймер RTC (Real-time clock):

* Для функции пробуждения необходимо установить бит WUTE в регистре RTC_CR, а также значение этого бита
* установить WUTWF в регистре RTC_ISR
* запрограммировать значение автоматической перезагрузки при пробуждении WUT[15:0 и выбрать время пробуждения (установить биты WUCKSEL[2:0] в регистре RTC_CR)]

=== Настройка подключения интерфейса USART2 для Bluetooth

* Подключить USART к источнику тактирования – устанавливаем бит USART2EN в регистре APB1ENR (АЦП тактируется от матрицы шин APB1).​
* Необходимо сконфигурировать порты. Настроить порты, на альтернативную функцию нужного модуля USART​
* Настроить формат передачи байт, с помощью регистра CR1 и CR2​
* Задать скорость передачи с помощью регистра BRR​
* Разрешить передачу помощью бита TE и если надо прием, с помощью бита RE в модуле USART с помощью регистра CR1​
* Включить сам модуль USART битом UE  в регистре CR1​
* Если работаем через прерывание, то разрешить глобальное прерывание для нужного USART, в регистре ISER[1] модуля NVIC​
* Если работаем через прерывание, в зависимости от того, что нам нужно, разрешить прерывание по сигналу модуля UART (например, от сигнала регистр данных передачика пуст (бит TXEIE в регистре CR1))

Полная настройка и др. представлено в коде main.cpp
[.source, cpp]
----
#include "rtos.hpp"         // for Rtos
#include "rccregisters.hpp" // for RCC
//#include "usart2registers.hpp" // for USART2
//#include "gpioaregisters.hpp" // for GPIOA


#include "MeasureGlycemiaTask.h" // for MeasureGlycemiaTask
#include "Temperature.h" // for Temperature
#include "Glycemia.h" // for Glycemia
#include "Frequency.h" // for Frequency
//#include "BluetoothTask.h" // for BluetoothTask
//#include "BatteryTask.h" // for BatteryTask

std::uint32_t SystemCoreClock = 16'000'000U;

extern "C" {
int __low_level_init(void)
{
  /*//Usart
  RCC::APB1ENR::USART2EN::Enable::Set(); // тактирование
  GPIOA::MODER::MODER2::Alternate::Set(); // конфигурация портов, альтернативная функция
  GPIOA::MODER::MODER3::Alternate::Set(); // конфигурация портов, альтернативная функция
  GPIOA::OTYPER::OT2::OutputPushPull::Set();
  GPIOA::OTYPER::OT3::OutputPushPull::Set();
  GPIOA::PUPDR::PUPDR2::PullUp::Set(); // подтяжка к 1  
  GPIOA::PUPDR::PUPDR3::PullUp::Set(); // подтяжка к 1 
  
  GPIOA::AFRL::AFRL2::Af7::Set();
  GPIOA::AFRL::AFRL3::Af7::Set();
  
  USART2::BRR::DIV_Mantissa::Set(104);
  USART2::BRR::DIV_Fraction::Value2::Set();
  USART2::CR2::STOP::Value0::Set();
    
  USART2::CR1::OVER8::OversamplingBy16::Set(); // Режим дискретизации? 1/16
  USART2::CR1::M::Data8bits::Set();
  
  USART2::CR1::TE::Enable::Set();
  USART2::CR1::UE::Enable::Set();*/
  
  return 1;
}
}

Temperature temp;
Glycemia glyc;
Frequency freq;

MeasureGlycemiaTask measureGlycemiaTask (glyc, temp, freq);

int main()
{  
  using namespace OsWrapper;
  Rtos::CreateThread(measureGlycemiaTask, "measureGlycemiaTask");
  
  Rtos::Start();
  
  return 0;
}
----

=== Архитектура
По полученным результатам анаализа требований была составлена архитектура программного обеспечения устройства.

[#Основная UML-диаграмма]
.Основная UML-диаграмма
[plantuml,format=png]
....
include::UMLMain.puml[]
....

Для передачи информации по Bluetooth создана отдельная архитектура (поддиаграмма).

[#UML-диаграмма измерения частоты]
.UML-диаграмма измерения частоты
[plantuml,format=png]
....
include::UMLTransmitor.puml[]
....

//[#Основная UML-диаграмма]
//.Основная UML-диаграмма
//[plantuml,format=png]
//....
//include::Diagram.puml[]
//....

//[#UML-диаграмма измерения частоты]
//.UML-диаграмма измерения частоты
//[plantuml,format=png]
//....
//include::PodDiagram.puml[]
//....