@startuml name 

interface IThread
interface IMeasureTemperatureTask
{
    +{abstract} void Temperature()
}
class Frequency
interface IMeasureFrequency
{
    (Метод 2х таймеров (описать 
    + возможно, перерисовать окружение))
}

IThread .. IMeasureTemperatureTask
Frequency -up-|> IMeasureTemperatureTask
IMeasureFrequency -up-o Frequency

interface ITemperatureGlycemiaTask
class Glycemia
interface BluetoothGlycemiaTask
interface USART2
class Bluetooth

IThread .. BluetoothGlycemiaTask
Bluetooth -up-|> BluetoothGlycemiaTask
ITemperatureGlycemiaTask -up-o Glycemia
USART2 -up-o Bluetooth
Glycemia -up-|> USART2

@enduml