@startuml name1 

interface IMeasureFrequency
class Frequency
{
    Преобразует полученные
    значения в частоту
}
interface ITimers
{
    Обеспечивает считывание
    информации полученной
    таймерами
}
class Timer2
{
    считает кол-во импульсов
    пришедших на него за
    время установленное
    таймером 5
}
interface IUpdate
{
    Обеспечивает передачу
    сигнала для начала 
    измерений
}
class Timer5
{
    + void {abstract} time
    Каждые (время) запускает
    таймер 2 (с частотой 
    32-45 кГц)
}

ITimers -up-o Frequency
Timer2 -up-|> ITimers
Timer5 -up-|> ITimers
Frequency -up-|> IMeasureFrequency
Timer2 o-right- IUpdate
IUpdate <|-right- Timer5

@enduml