@startuml Frequency 

interface IMeasureFrequency
{
    Обеспечивает передачу 
    информации о частоте 
}
class Frequency
{
    Преобразует полученные
    значения в частоту
}
interface ITimers
{
    Обеспечивает считывание
    информации полученной
    таймером
}
class Timer5
{
    Считает кол-во импульсов
    пришедших на него за период 
    переполнения таймера 2
}
class Temperature
{
    Преобразует частоту
    в температуру
}

ITimers -up-o Frequency
Timer5 -up-|> ITimers
Frequency -up-|> IMeasureFrequency
IMeasureFrequency -up-o Temperature

@enduml