@startuml DataProvider


class BatteryVoltage
{
Преобразует код АЦП
в значение заряда
батареи

+ void Calculate ()
+ void Provid ()
}

class Information
{
Преобразует информацию
в строку

+ {abstract} DataLine ()
}

interface IDataProvider
{
    Обеспечивает передачу 
    информации для дальнейшего 
    преобразования

    + void Provid () = 0
}

BatteryVoltage -up-|> IDataProvider
Information o--IDataProvider

class ADC
{
Считывает информацию
получаемую АЦП от
батареи

+ {abstract} Reading ()
}

interface IReader
{
    Обеспечивает
    считывание значений
    с АЦП

    {abstract} Reading () = 0
}

ADC -up-|> IReader
BatteryVoltage o--IReader

@enduml