@startuml DataProvider

class Glycemia
{
Преобразует полученные
значения температуры в
значения гликемии

+ float Calculate ()
+ float Provide ()
}

class Temperature
{
Преобразует частоту
в температуру

+ float Calculate ()
+ float Provide ()
}

class Frequency
{
Получает информацию
о значениях частоты

+ float Calculate ()
+ float Provide ()
}

class Information
{
Преобразует информацию
в строку

+ {abstract} DataLine ()
}

interface IDataProvider
{
    Обеспечивает передачу 
    информации для дальнейшего 
    преобразования

    + float Provide () = 0
}

Frequency -up-|> IDataProvider
Temperature -up-|> IDataProvider
Glycemia -up-|> IDataProvider

Glycemia o-- IDataProvider
Temperature o-- IDataProvider
Information o--IDataProvider

@enduml