@startuml Frequency 

interface IMeasureFrequency
{
    Обеспечивает передачу 
    информации о частоте 
}
class Frequency
{
    Преобразует полученные
    значения в частоту.

     + {abstract} CalculateFrequency ()
}

class Temperature
{
    Преобразует частоту
    в температуру
}

Frequency -up-|> IMeasureFrequency
IMeasureFrequency -up-o Temperature

@enduml