:imagesdir: images
:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:stem: Формула
:sourcedir: CODE


== Дизайн

Для корректной работы устройства необходимо произвести настройки используемых модулей.

=== Настройка подключения интерфейса USART2 для Bluetooth

* Подключить USART к источнику тактирования – устанавливаем бит USART2EN в регистре APB1ENR.​

* Настроить порты, на альтернативную функцию нужного модуля USART2​.

* Настроить формат передачи байт, с помощью регистра CR1 и CR2​.

* Задать скорость передачи с помощью регистра BRR, установить значение 800U

* Включить сам модуль USART2 битом UE в регистре CR1​.

* Разрешить глобальное прерывание для нужного USART, в регистре ISER[1] модуля NVIC, настроив на время равное 1 с​.

* Настроить порты PORT PD5 как TX, Port PD6 как RX на альтернативную функцию работы с UART в режим Push-Pull(двухтактный выход) + Pull Up(подтяжка к 1)​

* Настроить USART2 на скорость 9600 бит/c, 1 стоп бит, 1 старт бит, без проверки четности, режим дискретизации 1/16, 8 бит данных.


=== Архитектура
По полученным результатам анаализа требований была составлена архитектура программного обеспечения устройства.

[#Основная UML-диаграмма]
.Основная UML-диаграмма
[plantuml,format=png]
....
include::UMLMain.puml[]
....

*_Описание:_* раз в 5 минут планировщик вызывает задачи MeasureGlycemiaTask и BluetoothTask (активные классы). MeasureGlycemiaTask в свою очередь вызывает расчет гликемии (Glycemia) пересчитанное из значений темературы (Temperature), которые в свою очередь пересчитываются из значений измеренного изменения частоты (Frequency) через интерфейс ICalculate. +
Активный класс BluetoothTask через интерфейс IBluetooth  передает по беспроводному интерфейсу Bluetooth строки с запрошенной информацией.

Для описания каждого класса созданы отдельные архитектуры.

[#UML-диаграмма сообщения информации между классами]
.UML-диаграмма сообщения информации между классами
[plantuml,format=png]
....
include::UMLDataProvider.puml[]
....

*_Описание:_* интерфейс IDataProvider обеспечивает передачу значений из одного класса в другой, таким образом информация о частоте (Frequency) доступна классу температуры (Temperature), а информация о температуре доступна классу гликемии (Glycemia). +
Для передачи информации о гликемии по интерфесу Bluetooth также используется интерфейс IDataProvider, в InfoUsart полученная информация преобразуется в строку и через интерфейс IBluetotth передается по интерфейсу Bluetotth (см. [#Основная UML-диаграмма])