:toc: macro
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:stem: Формула
:sourcedir: CODE

== Введение

Сахарный диабет (СД) – группа эндокринных заболеваний, связанных с нарушением усвоения глюкозы и развивающихся вследствие абсолютной или относительной (нарушение взаимодействия с клетками-мишенями) недостаточности гормона инсулина, в результате чего развивается гипергликемия – стойкое увеличение содержания глюкозы в крови.

СД представляет собой глобальную медико-социальную проблему современности, с неуклонным ростом и развитием микро- и микрососудистых осложнений, определяющих качество жизни больных СД.

Достижение и длительное поддержание стабильной концентрации глюкозы в крови, максимально близкой к физиологической норме, - основная цель лечения СД.

Общая численность пациентов с СД в Российской Федерации, состоящих на диспансерном учете, на 01.07.2022 г., по данным регистра, составила 4 834 151 (3,25% населения РФ).

Для контроля течения заболевания используют глюкометр и шприц-ручку, или её более современный аналог инсулиновую помпу.

Глюкометр – прибор для измерения уровня глюкозы в органических жидкостях (кровь, ликвор и тому подобное).

Определение уровня глюкозы крови — один из самых распространенных тестов, выполняемых клинико-диагностическими лабораториями. Причина исключительной популярности теста связана с высокой заболеваемостью сахарным диабетом. Данный тест выполняется как в условиях стационара, так и в поликлиниках. Больные сахарным диабетом вынуждены исследовать уровень глюкозы в крови в домашних условиях, поскольку без этой информации им трудно скорректировать свою диету, физические нагрузки, применение (рсчитать необходиую дозировку) инсулина и других сахароснижающих препаратов.

Самый первый вопрос, который возникает – это как измерить уровень глюкозы в крови, если нет специально лабораторного оборудования. 

В настоящее время измерения глюкозы производятся путем прокалывания пальца и извлечения капли крови, которая применяется к тест-полоски, состоящей из химических веществ, чувствительных к глюкозе в образце крови. Оптический измеритель (глюкометр) используется для анализа пробы крови и дает числовое значение содержания глюкозы. 

Сегодня широко распространены глюкометры, предназначенные для домашнего использования. Это компактные приборы, помогающие поддерживать хорошую компенсацию людям с сахарным диабетом.

Самым главным недостатком глюкометаявляется его инвазивность, т.е. необходимо обязательно проколоть палец, т.е. нарушить структуру тканей человеческого организма и тем самым сильно потревожить, а в последствии и повредить нервной системе пациента. Так как в следствие многочисленных проколов (в одних и тех же местах) организм человека не успевает восстанавливать структуру ткани и нервную систему, что является причиной потери чувствительности, в местах прокола.

Именно поэтому необходимо разработать устройство "неинвазивный глюкометр", который с помощью метода  термоспектроскопии (неинвазивный метод) определяет уровень глюкозы в крови человека, и передает полученные данные по Bluetooth на управляющее устройство.
